// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTL9eEsRsWrgEj6a6Tt7PVKyr8f9vrJd4',
    appId: '1:340226665938:web:1d3139eaacb8b722aa6c0b',
    messagingSenderId: '340226665938',
    projectId: 'smartcurb-d174e',
    authDomain: 'smartcurb-d174e.firebaseapp.com',
    databaseURL: 'https://smartcurb-d174e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcurb-d174e.firebasestorage.app',
    measurementId: 'G-RK4N8WVDBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHJJna9q578H21T7p-KzmsYwDj8WSSZd8',
    appId: '1:340226665938:android:e9a0309f488dea28aa6c0b',
    messagingSenderId: '340226665938',
    projectId: 'smartcurb-d174e',
    databaseURL: 'https://smartcurb-d174e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcurb-d174e.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5lBmCrpEzNACE75_eDQPJSnGqSzmBGC8',
    appId: '1:340226665938:ios:094bd7e44cb4e9e5aa6c0b',
    messagingSenderId: '340226665938',
    projectId: 'smartcurb-d174e',
    databaseURL: 'https://smartcurb-d174e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcurb-d174e.firebasestorage.app',
    iosBundleId: 'com.example.smartCurb',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5lBmCrpEzNACE75_eDQPJSnGqSzmBGC8',
    appId: '1:340226665938:ios:094bd7e44cb4e9e5aa6c0b',
    messagingSenderId: '340226665938',
    projectId: 'smartcurb-d174e',
    databaseURL: 'https://smartcurb-d174e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcurb-d174e.firebasestorage.app',
    iosBundleId: 'com.example.smartCurb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTL9eEsRsWrgEj6a6Tt7PVKyr8f9vrJd4',
    appId: '1:340226665938:web:e86a30efcda7aa02aa6c0b',
    messagingSenderId: '340226665938',
    projectId: 'smartcurb-d174e',
    authDomain: 'smartcurb-d174e.firebaseapp.com',
    databaseURL: 'https://smartcurb-d174e-default-rtdb.firebaseio.com',
    storageBucket: 'smartcurb-d174e.firebasestorage.app',
    measurementId: 'G-22ZEWX8N2K',
  );
}
